BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER NOT NULL,
	"username"	TEXT NOT NULL,
	"password"	TEXT NOT NULL,
	"isAdmin"	BOOL NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "users" VALUES (1,'admin','$2y$10$rYnuiVwlzBIY8oVzgPgKHe22a313o/IK16AiLEHox7ylcwdvYCdGW',1);
COMMIT;